version: '3.8'

services:

  parking_backend:
    build: backend/.
    container_name: parking_backend
    network_mode: "host"
    restart: unless-stopped
    

  parking_frontend:
    build: frontend/.
    container_name: parking_frontend
    ports:
      - '8080:80'
    restart: unless-stopped  
    